apiVersion: v1
kind: ServiceAccount
metadata:
  name: account-service
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: account-service-role
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["delete"]
- apiGroups: [""]
  resources: ["services"]
  verbs: ["delete"]
- apiGroups: ["batch"]
  resources: ["cronjobs"]
  verbs: ["delete"]
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["get", "patch"]
- apiGroups: [""]
  resources: ["persistentvolumeclaims"]
  verbs: ["create", "delete"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: account-service-rolebinding
subjects:
- kind: ServiceAccount
  name: account-service
roleRef:
  kind: Role
  name: account-service-role
  apiGroup: rbac.authorization.k8s.io
