apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: web-volume-claim-$(deploymentName)
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: azure-disk-web
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: web-volume-claim-log-$(deploymentName)
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: azure-disk-web
  resources:
    requests:
      storage: 5Gi