apiVersion: v1
kind: ConfigMap
metadata:
  name: web-config-$(deploymentName)
data:
  connectionStrings.config: |
    <?xml version="1.0" encoding="utf-8"?>
    <!--
    For more information on how to configure your ASP.NET application, please visit
    http://go.microsoft.com/fwlink/?LinkId=169433
    -->
    <configuration>
      <configSections>
        <section name="log4net" type="log4net.Config.Log4NetConfigurationSectionHandler,Log4net" requirePermission="false" />
        <section name="dataConfiguration" type="Microsoft.Practices.EnterpriseLibrary.Data.Configuration.DatabaseSettings, Microsoft.Practices.EnterpriseLibrary.Data, Version=5.0.505.0,Culture=neutral, PublicKeyToken=31BF3856AD364E35" />
        <sectionGroup name="businessObjects">
          <sectionGroup name="crystalReports">
            <section name="crystalReportViewer" type="System.Configuration.NameValueSectionHandler" />
          </sectionGroup>
        </sectionGroup>
      </configSections>
      <dataConfiguration defaultDatabase="ASOFT_ERP" />
      <businessObjects>
        <crystalReports>
          <crystalReportViewer>
            <add key="resourceURI" value="\crystalreportviewers13" />
          </crystalReportViewer>
        </crystalReports>
      </businessObjects>
      <!-- SQL Connection string config -->
      <connectionStrings>
        <add name="ASOFT_ERP" providerName="System.Data.SqlClient" connectionString="Server=mssql.minhnhut.online;Database=1BOSS_$(deploymentName);User ID=sa; Password=pa55w0rd!; Trusted_Connection=False;" />  
        <add name="ASOFT_ADMIN" providerName="System.Data.SqlClient" connectionString="Server=mssql.minhnhut.online;Database=AS_ADMIN_1BOSS_$(deploymentName);User ID=sa; Password=pa55w0rd!; Trusted_Connection=False;"/> 
      </connectionStrings>
      <appSettings>
        <add key="TimeReload" value="90000" />
      <add key="webpages:Version" value="2.0.0.0" />
        <add key="webpages:Enabled" value="false" />
        <add key="PreserveLoginUrl" value="true" />
        <add key="ClientValidationEnabled" value="true" />
        <add key="UnobtrusiveJavaScriptEnabled" value="true" />
        <add key="aspnet:MaxJsonDeserializerMembers" value="150000" />
      <!-- End auto service config -->
      <!-- Email SMTP and File storage location config -->
        <add key="UserID" value="info@asoft.com.vn" />
        <add key="Password" value="" />
        <add key="EnableSsl" value="true" />
        <add key="SMTP" value="smtp.gmail.com" />
        <add key="Port" value="465" />
        <add key="Domain" value="ASOFT.COM" />
        <add key="UserNet" value="administrator" />
        <add key="PasswordNet" value="" />
        <add key="Network_Drive" value="Z:" />
      <!-- End email SMTP and File storage location config -->
      </appSettings>
      <!--SMTP for XuongRong project -->
      <system.net>
        <mailSettings>
          <smtp>
            <network host="smpt.gmail.com" />
          </smtp>
        </mailSettings>
      </system.net>
      <!--End SMTP for XuongRong project -->
      <system.web>
        <customErrors mode="Off"/>
        <sessionState mode="Custom" customProvider="MySessionStateStore" timeout="20" >
          <providers>
          <add name="MySessionStateStore" type="Microsoft.Web.Redis.RedisSessionStateProvider"
            host="web.redis.cache.windows.net"
            accessKey="IXTyURqkVZ4N3sVj3kMmqRWLzYsKKxLuuAzCaIwOXfw="
            applicationName = "web_$(deploymentName)"
            ssl="false" />
          </providers>
        </sessionState>
        <authentication mode="Forms">
          <forms loginUrl="~/Login" timeout="40" />
        </authentication>
        <compilation targetFramework="4.5.1" debug="false">
          <assemblies>
            <add assembly="Microsoft.Practices.EnterpriseLibrary.Data, Version=5.0.505.0,Culture=neutral, PublicKeyToken=31BF3856AD364E35" />
            <add assembly="System.Web.Abstractions, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31BF3856AD364E35" />
            <add assembly="System.Web.Routing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31BF3856AD364E35" />
            <add assembly="System.Web.Mvc, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" />
            <add assembly="System.Web.WebPages, Version=2.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" />
            <add assembly="System.Web.Helpers, Version=2.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" />
            <add assembly="Microsoft.Build.Framework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=B03F5F7F11D50A3A" />
            <add assembly="System.Management, Version=4.0.0.0, Culture=neutral, PublicKeyToken=B03F5F7F11D50A3A" />
        <add assembly="System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" />
          </assemblies>
        </compilation>
        <pages validateRequest="false" clientIDMode="AutoID" controlRenderingCompatibilityVersion="4.0">
          <namespaces>
            <add namespace="System.Web.Helpers" />
            <add namespace="System.Web.Mvc" />
            <add namespace="System.Web.Mvc.Ajax" />
            <add namespace="System.Web.Mvc.Html" />
            <add namespace="System.Web.Routing" />
            <add namespace="System.Web.WebPages" />
            <add namespace="Kendo.Mvc.UI" />
          </namespaces>
        </pages>
        <globalization uiCulture="en-GB" culture="en-GB" enableClientBasedCulture="false" />
      <!-- target build and target framework must the same version -->
        <httpRuntime targetFramework="4.5.1" maxRequestLength="2147483647" requestLengthDiskThreshold="512" relaxedUrlToFileSystemMapping="true" executionTimeout="110" requestPathInvalidCharacters="&lt;,&gt;,*,%,:,&amp;,\" />
      </system.web>
      <system.webServer>
        <modules runAllManagedModulesForAllRequests="true" />
        <validation validateIntegratedModeConfiguration="false" />
        <handlers>
          <remove name="ExtensionlessUrlHandler-ISAPI-4.0_32bit" />
          <remove name="ExtensionlessUrlHandler-ISAPI-4.0_64bit" />
          <remove name="ExtensionlessUrlHandler-Integrated-4.0" />
          <add name="ExtensionlessUrlHandler-ISAPI-4.0_32bit" path="*." verb="GET,HEAD,POST,DEBUG,PUT,DELETE,PATCH,OPTIONS" modules="IsapiModule" scriptProcessor="%windir%\Microsoft.NET\Framework\v4.0.30319\aspnet_isapi.dll" preCondition="classicMode,runtimeVersionv4.0,bitness32" responseBufferLimit="0" />
          <add name="ExtensionlessUrlHandler-ISAPI-4.0_64bit" path="*." verb="GET,HEAD,POST,DEBUG,PUT,DELETE,PATCH,OPTIONS" modules="IsapiModule" scriptProcessor="%windir%\Microsoft.NET\Framework64\v4.0.30319\aspnet_isapi.dll" preCondition="classicMode,runtimeVersionv4.0,bitness64" responseBufferLimit="0" />
          <add name="ExtensionlessUrlHandler-Integrated-4.0" path="*." verb="GET,HEAD,POST,DEBUG,PUT,DELETE,PATCH,OPTIONS" type="System.Web.Handlers.TransferRequestHandler" preCondition="integratedMode,runtimeVersionv4.0" />
          <remove name="MvcResourceHandler" />
          <remove name="ExtensionlessUrlHandler-ISAPI-4.0_32bit" />
          <remove name="ExtensionlessUrlHandler-ISAPI-4.0_64bit" />
          <remove name="ExtensionlessUrlHandler-Integrated-4.0" />
          <add name="ExtensionlessUrlHandler-ISAPI-4.0_32bit" path="*." verb="GET,HEAD,POST,DEBUG,PUT,DELETE,PATCH,OPTIONS" modules="IsapiModule" scriptProcessor="%windir%\Microsoft.NET\Framework\v4.0.30319\aspnet_isapi.dll" preCondition="classicMode,runtimeVersionv4.0,bitness32" responseBufferLimit="0" />
          <add name="ExtensionlessUrlHandler-ISAPI-4.0_64bit" path="*." verb="GET,HEAD,POST,DEBUG,PUT,DELETE,PATCH,OPTIONS" modules="IsapiModule" scriptProcessor="%windir%\Microsoft.NET\Framework64\v4.0.30319\aspnet_isapi.dll" preCondition="classicMode,runtimeVersionv4.0,bitness64" responseBufferLimit="0" />
          <add name="ExtensionlessUrlHandler-Integrated-4.0" path="*." verb="GET,HEAD,POST,DEBUG,PUT,DELETE,PATCH,OPTIONS" type="System.Web.Handlers.TransferRequestHandler" preCondition="integratedMode,runtimeVersionv4.0" />
        </handlers>
        <security>
          <requestFiltering allowDoubleEscaping="true" />
        </security>
      </system.webServer>
      <system.web.extensions>
        <scripting>
          <webServices>
            <jsonSerialization maxJsonLength="2147483644" />
          </webServices>
        </scripting>
      </system.web.extensions>
      <!-- Log detail config -->
      <log4net>
        <appender name="RollingFileAppender" type="log4net.Appender.RollingFileAppender">
          <file type="log4net.Util.PatternString">
            <conversionPattern value="./Logs/asoft%date{yyyyMMdd}.log" />
          </file>
          <appendToFile value="true" />
          <rollingStyle value="Date" />
          <!-- <layout type="log4net.Layout.PatternLayout">
            <conversionPattern value="%-14%date{yyyyMMddhhmmss} %-5level - %message%newline" />
          </layout> -->
          <datePattern value="yyyyMMdd'.log'" />
          <layout type="log4net.Layout.PatternLayout">
          <conversionPattern value="%date [%thread] %-5level - %message%newline" />
          </layout>
        </appender>
        <logger name="AsoftLog">
          <appender-ref ref="RollingFileAppender" />
        </logger>
        <appender name="ConsoleAppender" type="log4net.Appender.ConsoleAppender">
          <layout type="log4net.Layout.PatternLayout">
            <conversionPattern value="%date [%thread] %-5level %logger [%ndc] - %message%newline" />
          </layout>
        </appender>
        <root>
          <level value="DEBUG" />
          <appender-ref ref="ConsoleAppender" />
        </root>
      </log4net>
      <!-- End log detail config -->
      <runtime>
        <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
          <dependentAssembly>
            <assemblyIdentity name="System.Web.Helpers" publicKeyToken="31bf3856ad364e35" />
            <bindingRedirect oldVersion="1.0.0.0-2.0.0.0" newVersion="2.0.0.0" />
          </dependentAssembly>
          <dependentAssembly>
            <assemblyIdentity name="System.Web.Mvc" publicKeyToken="31bf3856ad364e35" />
            <bindingRedirect oldVersion="0.0.0.0-4.0.0.0" newVersion="4.0.0.0" />
          </dependentAssembly>
          <dependentAssembly>
            <assemblyIdentity name="System.Web.WebPages" publicKeyToken="31bf3856ad364e35" />
            <bindingRedirect oldVersion="0.0.0.0-2.0.0.0" newVersion="2.0.0.0" />
          </dependentAssembly>
          <dependentAssembly>
            <assemblyIdentity name="Microsoft.Practices.Unity" publicKeyToken="31bf3856ad364e35" culture="neutral" />
            <bindingRedirect oldVersion="0.0.0.0-2.1.505.0" newVersion="2.1.505.0" />
          </dependentAssembly>
          <dependentAssembly>
            <assemblyIdentity name="Microsoft.Practices.Unity.Interception" publicKeyToken="31bf3856ad364e35" culture="neutral" />
            <bindingRedirect oldVersion="0.0.0.0-2.1.505.0" newVersion="2.1.505.0" />
          </dependentAssembly>
          <dependentAssembly>
            <assemblyIdentity name="WebGrease" publicKeyToken="31bf3856ad364e35" culture="neutral" />
            <bindingRedirect oldVersion="0.0.0.0-1.3.0.0" newVersion="1.3.0.0" />
          </dependentAssembly>
          <dependentAssembly>
            <assemblyIdentity name="Microsoft.Owin" publicKeyToken="31bf3856ad364e35" culture="neutral" />
            <bindingRedirect oldVersion="0.0.0.0-2.0.2.0" newVersion="2.0.2.0" />
          </dependentAssembly>
          <dependentAssembly>
            <assemblyIdentity name="Microsoft.Owin.Security" publicKeyToken="31bf3856ad364e35" culture="neutral" />
            <bindingRedirect oldVersion="0.0.0.0-2.0.2.0" newVersion="2.0.2.0" />
          </dependentAssembly>
          <dependentAssembly>
            <assemblyIdentity name="Newtonsoft.Json" publicKeyToken="30ad4fe6b2a6aeed" culture="neutral" />
            <bindingRedirect oldVersion="0.0.0.0-12.0.0.0" newVersion="12.0.0.0" />
          </dependentAssembly>
        </assemblyBinding>
      <!-- GC collection config -->
      <gcServer enabled="true"/>
        <gcConcurrent enabled="true"/>
      <!-- End GC collection config -->
      </runtime>
    </configuration>
